# Generated by Django 2.1.1 on 2018-10-29 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 29, 17, 27, 59, 139266)),
        ),
        migrations.AddField(
            model_name='food',
            name='delivered_at',
            field=models.CharField(default='NAN', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='donor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.Donor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.CharField(default='NAN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Picked', 'Picked'), ('New Entry', 'New Entry')], default='FAST FOOD', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Regular Food', 'Regular Food'), ('Fast Food', 'Fast Food')], max_length=15),
        ),
    ]
