# Generated by Django 2.1.1 on 2018-10-29 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20181029_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 29, 17, 31, 17, 150953, tzinfo=utc)),
        ),
    ]
