# Generated by Django 2.1.1 on 2018-10-29 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20181029_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 29, 17, 33, 33, 245546, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('New Entry', 'New Entry'), ('Picked', 'Picked')], max_length=10),
        ),
    ]
