# Generated by Django 2.1.1 on 2018-10-30 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20181029_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 30, 21, 11, 29, 194616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Fast Food', 'Fast Food'), ('Regular Food', 'Regular Food')], max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Picked', 'Picked'), ('New Entry', 'New Entry')], max_length=10),
        ),
    ]
