# Generated by Django 2.1.1 on 2018-11-04 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20181030_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='Date',
        ),
        migrations.AddField(
            model_name='food',
            name='food_title',
            field=models.CharField(default='NAN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 4, 13, 33, 22, 959129, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 4, 13, 33, 22, 959129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Regular Food', 'Regular Food'), ('Fast Food', 'Fast Food')], max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('New Entry', 'New Entry'), ('Picked', 'Picked')], max_length=10),
        ),
    ]
