# Generated by Django 2.1.1 on 2018-11-05 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20181104_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='donor',
        ),
        migrations.AddField(
            model_name='food',
            name='donor',
            field=models.ManyToManyField(to='donor.Donor'),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 5, 2, 20, 24, 841380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 5, 2, 20, 24, 841294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Delivered', 'Delivered'), ('Picked', 'Picked')], default='New Entry', max_length=10),
        ),
    ]
