# Generated by Django 2.1.1 on 2018-11-07 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
        ('donor', '0009_auto_20181105_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.Volenteer'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Regular Food', 'Regular Food'), ('Fast Food', 'Fast Food')], max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 7, 7, 33, 35, 805309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 7, 7, 33, 35, 805254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Delivered', 'Delivered'), ('New Entry', 'New Entry')], default='New Entry', max_length=10),
        ),
    ]
