# Generated by Django 2.1.3 on 2018-11-11 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_auto_20181111_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 11, 9, 19, 33, 714248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 11, 9, 19, 33, 714190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('Delivered', 'Delivered'), ('New Entry', 'New Entry')], default='New Entry', max_length=10),
        ),
    ]
