# Generated by Django 2.1.3 on 2018-11-11 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_auto_20181111_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='map_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='map_logitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Fast Food', 'Fast Food'), ('Regular Food', 'Regular Food')], max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 11, 22, 46, 36, 633695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 11, 22, 46, 36, 633632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Picked', 'Picked'), ('New Entry', 'New Entry')], default='New Entry', max_length=10),
        ),
    ]
