# Generated by Django 2.1.1 on 2018-11-18 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_auto_20181118_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Regular Food', 'Regular Food'), ('Fast Food', 'Fast Food')], max_length=15),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 18, 16, 49, 57, 113652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 18, 16, 49, 57, 113652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Picked', 'Picked'), ('New Entry', 'New Entry')], default='New Entry', max_length=10),
        ),
    ]
