# Generated by Django 2.1.4 on 2018-12-10 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_auto_20181126_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='gallery',
            field=models.ManyToManyField(to='donor.FoodImage'),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 10, 2, 57, 3, 469310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 10, 2, 57, 3, 469244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Delivered', 'Delivered'), ('Picked', 'Picked')], default='New Entry', max_length=10),
        ),
    ]
