# Generated by Django 2.1.4 on 2018-12-10 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0021_auto_20181210_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 10, 3, 57, 58, 667228, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 10, 3, 57, 58, 667150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Picked', 'Picked'), ('New Entry', 'New Entry'), ('Delivered', 'Delivered')], default='New Entry', max_length=10),
        ),
    ]
