# Generated by Django 2.1.3 on 2018-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdsadmin', '0003_fdsadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdsadmin',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
