# Generated by Django 2.1.1 on 2018-11-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdsadmin', '0005_auto_20181118_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdsadmin',
            name='gender',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
    ]
