# Generated by Django 2.1.4 on 2018-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdsadmin', '0008_auto_20181126_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdsadmin',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
