# Generated by Django 2.1.3 on 2018-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volenteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
