# Generated by Django 2.1.3 on 2018-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volenteer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volenteer',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volenteer',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volenteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=6, null=True),
        ),
    ]
