# Generated by Django 2.1.3 on 2018-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20181111_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volenteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='volenteer',
            name='pick_locations',
            field=models.ManyToManyField(help_text='press ctrl and click to select multiple', to='volunteer.Location'),
        ),
    ]
